; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Studentai
AppVersion=3.0
DefaultDirName={pf}\Studentai
DefaultGroupName=Studentai
UninstallDisplayIcon={app}\Studentai.exe
OutputBaseFilename=Setup
Compression=lzma
SolidCompression=yes

[Files]
Source: "main.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Studentai"; Filename: "{app}\main.exe"
Name: "{commondesktop}\Studentai"; Filename: "{app}\.exe"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop icon"

[Run]
Filename: "{app}\main.exe"; Description: "Launch My Application"; Flags: nowait postinstall skipifsilent
